### ISSUE TITLE
Como altero o idioma de acordo com as configurações regionais do dispositivo?

### ISSUE THREAD

**Issue by NestorDevs** [davidsdearaujo/localization#1]
Eu tenho um aplicativo com dois idiomas ... inglês e espanhol ... já está traduzido usando este plug-in ... mas observo que se eu alterar a configuração regional do dispositivo e alterá-lo para inglês, os textos permanecem em espanhol ... como conseguir isso? com seus plugins?

**Comment by toshiossada** [comment]
PR aberta aguardando aprovação https://github.com/davidsdearaujo/localization/pull/2

**Comment by davidsdearaujo** [comment]
Adicionamos a feature mas, por enquanto, está disponível apenas na branch DEV 
_(será publicado no [pub.dev](https://pub.dev/packages/localization) em breve)_

Caso já queira testar, utilize a referência da branch `dev` antes da publicação oficial no [pub.dev](https://pub.dev/packages/localization).
Para isso, basta colocar no `pubspec.yaml` essa referência:
```yaml
  localization:
    git: 
      url: git://github.com/davidsdearaujo/localization.git
      ref: dev
```
